name: SeeDevice
main: Palente\SeeDevice\SeeDevice
author: Palente
api: 4.0.0
version: 1.2.0
description: "More easy to get the Device/OS of a Player"

commands:
  seedevice:
    description: "See The device of a player"
    permission: SeeDevice.seedevice
    usage: "/seedevice [player]"
  fakeos:
    description: "Change the device"
    permission: SeeDevice.fakeos
    usage: "/fakeos <player-self> <name_of_device>"

permissions:
  SeeDevice.fakeos:
    default: op
  SeeDevice.seedevice:
    default: op
